version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    command: >
      /bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_stomp && rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit-default

  nginx:
    image: nginx:latest
    container_name: rabbit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - rabbit-default

networks:
  rabbit-default:
