spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rabbitmq?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/message_history?authSource=admin&authMechanism=SCRAM-SHA-1
      username: root
      password: 1234
    redis:
      host: localhost
      port: 6379

jwt:
  secret: lsh2613 #jwt secret key
  access:
    expiration: 1800000
    header: Authorization
  refresh:
    expiration: 259200000
    header: Authorization-Refresh

rabbitmq:
  host: "localhost"
  port: 5672
  virtual-host: "/"
  username: "guest"
  password: "guest"
  relay:
    port: 61613
    system-login: guest
    system-passcode: guest
    client-login: guest
    client-passcode: guest
  chat:
    queue:
      name: "chat.queue"
    exchange:
      name: "chat.exchange"
    routing:
      key: "*.room."

logging:
  level:
    org.springframework.data.redis.connection: DEBUG
    org.springframework.cache: DEBUG
