name: 'Auto Assign'
on:
  pull_request:
    types: [ opened, ready_for_review ]

jobs:
  add-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/config/auto-assign-config.yml
          # Settings -> Actions -> General -> Workflow permissions -> Read and write permissions 권한 필요
