name: Draft new release
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: config/drafter-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
